export const enum ReportType {
  SET_REPORT = 'SET_REPORTS',
  SET_TEAM = 'SET_TEAM',
  ADD_REPORT = 'ADD_REPORT',
  EDIT_REPORT = 'EDIT_REPORT',
  SET_USER_ACTIVITY = 'SET_USER_ACTIVITY',
  EDIT_USER_ACTIVITY = 'EDIT_USER_ACTIVITY'
}